stages:
  - deploy

deploy_to_server:
  image: 1000i100/docker-ci-cd-publish:latest
  stage: deploy
  tags:
    - docker-runner
  before_script:
    - apk add --no-cache openssh sshpass rsync
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - cd og-images && ./convert.sh && cd ..
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
      --exclude='.git*' \
      --exclude='*.yml' \
      ./ gammanu@gamma.nu:/home/gammanu/unanym/
