stages:
  - deploy

variables:
  PROJECT_NAME: "unanym"
  PROJECT_PATH: "/home/gammanu/${PROJECT_NAME}/"
  SSH_URI: "gammanu@gamma.nu"

deploy_to_server:
  image: 1000i100/docker-ci-cd-publish:latest
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - >-
      [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >
      ~/.ssh/config
  script:
    - ls -la
    - ssh -p $SSH_PORT $SSH_URI "ls -la $PROJECT_PATH"
    - rsync -avz -e "ssh -p $SSH_PORT" \
      --exclude='.git*' \
      --exclude='*.yml' \
      ./ $SSH_URI:$PROJECT_PATH
