stages:
  - deploy

deploy_to_server:
  image: 1000i100/docker-ci-cd-publish:latest
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - >-
      [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >
      ~/.ssh/config
  script:
    - rsync -avz -e "ssh -p $SSH_PORT" \
      --exclude='.git*' \
      --exclude='*.yml' \
      ./ gammanu@gamma.nu:/home/gammanu/unanym/
